Fix for screens with a higher than 1 pixel ratio
Crunch-io/nightwatch-vrt pull request #20
Opened 2018-03-27 12:28 UTC by gregoryduckworth

Added check that if the device has a greater than 1 devicePixelRatio, then we update the width and height to these values. This allows displays with a denser pixel ratio to crop and resize without any issues.

2018-03-27 15:55 UTC, turbuorange requested changes
x and y values needs to be scaled too

2018-03-27 15:55 UTC, turbuorange commented on commands/captureElementScreenshot.js
> +          if (devicePixelRatio.value > 1) {
x and y values needs to be scaled too

2018-03-28 09:00 UTC, kimulus approved these changes

2018-03-28 13:25 UTC, turbuorange approved these changes

2018-08-11 15:08 UTC, michaeljacobdavis commented
Ran into this on my mbp and was super confused why it was only taking a screenshot of a portion of the screen (was targeting `body`).

Any chance we can get this merged in soon? Happy to help in any way.

2018-08-13 16:25 UTC, msteitle requested changes
Good change. Thanks. Left two small comments.

2018-08-13 16:25 UTC, msteitle commented on commands/captureElementScreenshot.js
> +          if (devicePixelRatio.value > 1) {
I'd just remove this conditional. If the ratio === 1, then there will be no effect. Doing four product functions won't affect performance.

2018-08-13 16:25 UTC, msteitle commented on commands/captureElementScreenshot.js
> +          if (devicePixelRatio.value > 1) {
There is no linting going on here, so I feel obligated to mention that indentation is 4 spaces. Thanks!

2018-08-15 15:55 UTC, michaeljacobdavis commented
Thanks @gregoryduckworth!

@msteitle if all looks good, mind doing a merge and publishing? Looking forward to using this 😄

2018-09-05 02:12 UTC, michaeljacobdavis commented
@msteitle Sorry to bump this but would be awesome to get this merged. Can you approve and publish?

2018-09-11 18:27 UTC, amarbir22 commented
I can confirm the issue on MacBook Pro (Retina, 15-inch, Mid 2015), running Chrome Version 68.0.3440.106 (Official Build) (64-bit). The screenshot taken is half the size.
Also, I can confirm the issue does resolve if running in a Docker container. If possible please merge the changes at earliest.

2018-09-24 13:39 UTC, aberonni commented
Bump, also interested in getting this merged. @msteitle is there anything we can do to speed this up?

2018-09-28 12:02 UTC, aberonni commented
@bertjwregeer any chance you could get this merged? I see you as the main person in charge of Crunch-io repositories and there are quite a few that would like to see this merged

2018-09-28 12:08 UTC, aberonni commented
Poking @enriquecastl as well who seems to be the latest maintainer

2018-09-30 17:53 UTC, michaeljacobdavis commented
For what it's worth, I switched to https://github.com/bbc/nightwatch-vrt. Has the changes.

2018-09-30 23:33 UTC, bertjwregeer commented
I can merge this, but I am not sure who has the power to publish the new package to NPM. I'll poke people internally.

2018-09-30 23:33 UTC, merged